# Generated by Django 5.1.4 on 2025-04-23 02:30

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=50)),
                ('Tdeteil', models.CharField(max_length=255)),
                ('Tfrom', models.CharField(max_length=100)),
                ('Tplace', models.CharField(max_length=100)),
                ('Command', models.CharField(max_length=150)),
                ('Tdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('name_e', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(blank=True, null=True)),
                ('Prov_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Dstr_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('District_Name', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('dmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province_LCIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prov_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('Province_Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('sid_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(blank=True, null=True)),
                ('Prov_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Dstr_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Vill_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Village_Name', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document_format',
            fields=[
                ('dmf_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('insert_date', models.CharField(max_length=255, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='document_general',
            fields=[
                ('docg_id', models.AutoField(primary_key=True, serialize=False)),
                ('insert_date', models.CharField(blank=True, max_length=15, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('en_date', models.DateField(blank=True, null=True)),
                ('status_doc', models.CharField(default='0', max_length=20)),
                ('doc_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(max_length=500, null=True, upload_to=api.models.general_document_directory_path)),
                ('document_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_lcic_general', to='api.department')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.document_format')),
            ],
        ),
        migrations.CreateModel(
            name='document_lcic',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('insert_date', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_type_info', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(max_length=500, null=True, upload_to=api.models.department_directory_path)),
                ('document_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status2', models.CharField(default='new', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_lcic_department', to='api.department')),
                ('department_into', models.ManyToManyField(blank=True, related_name='document_lcic_department_into', to='api.department')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.document_format')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_lcic',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('lao_name', models.CharField(max_length=100)),
                ('eng_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(max_length=100)),
                ('birth_date', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('year_entry', models.CharField(null=True)),
                ('salary_level', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('pic', models.ImageField(null=True, upload_to='emp_img/')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('dom_abrd', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_num', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('action_type', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_num', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('award_type', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, max_length=255, null=True)),
                ('eth', models.CharField(blank=True, max_length=100, null=True)),
                ('rel', models.CharField(blank=True, max_length=100, null=True)),
                ('occ', models.CharField(blank=True, max_length=255, null=True)),
                ('work', models.CharField(blank=True, max_length=255, null=True)),
                ('vill', models.CharField(blank=True, max_length=100, null=True)),
                ('dist', models.CharField(blank=True, max_length=100, null=True)),
                ('prov', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, max_length=100, null=True)),
                ('prof', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, max_length=100, null=True)),
                ('eth', models.CharField(blank=True, max_length=100, null=True)),
                ('rel', models.CharField(blank=True, max_length=100, null=True)),
                ('b_vill', models.CharField(blank=True, max_length=100, null=True)),
                ('b_dist', models.CharField(blank=True, max_length=100, null=True)),
                ('b_prov', models.CharField(blank=True, max_length=100, null=True)),
                ('c_vill', models.CharField(blank=True, max_length=100, null=True)),
                ('c_dist', models.CharField(blank=True, max_length=100, null=True)),
                ('c_prov', models.CharField(blank=True, max_length=100, null=True)),
                ('gov_entry', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('youth_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('women_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('union_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('party_cand_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('full_party_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('curr_party_pos', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('party_apt_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('curr_gov_pos', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gov_apt_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalTheoryEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('dom_abrd', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializedEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('inst', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('dom_abrd', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('sta_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.CharField(max_length=255)),
                ('Sidebar', models.ManyToManyField(blank=True, related_name='status_roles', to='api.sidebar')),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='Document_Status',
            fields=[
                ('docstat_id', models.AutoField(primary_key=True, serialize=False)),
                ('Doc_status', models.CharField(default='viewed', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.document_lcic')),
                ('us_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_statuses', to='api.systemuser')),
            ],
            options={
                'unique_together': {('doc_id', 'us_id')},
            },
        ),
        migrations.AddField(
            model_name='document_lcic',
            name='status',
            field=models.ManyToManyField(blank=True, through='api.Document_Status', to='api.systemuser'),
        ),
        migrations.AddField(
            model_name='document_format',
            name='us_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.systemuser'),
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=255, null=True)),
                ('end', models.CharField(blank=True, max_length=255, null=True)),
                ('subj', models.CharField(blank=True, max_length=255, null=True)),
                ('inst', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.CharField(blank=True, max_length=100, null=True)),
                ('end', models.CharField(blank=True, max_length=100, null=True)),
                ('gov_pos', models.CharField(blank=True, max_length=255, null=True)),
                ('party_pos', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
    ]
