# Generated by Django 5.1.4 on 2025-04-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='id',
            new_name='pos_id',
        ),
    ]
