# Generated by Django 5.1.4 on 2025-04-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_id_position_pos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('sal_id', models.AutoField(primary_key=True, serialize=False)),
                ('Salary_Grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salarygrade')),
                ('pos_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
    ]
