# Generated by Django 5.1.4 on 2025-04-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='Salary_Grade',
        ),
        migrations.AddField(
            model_name='salary',
            name='SalaryGrade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
