# Generated by Django 5.1.4 on 2025-05-13 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_salary_salary_grade_salary_salarygrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPerformanceGrant',
            fields=[
                ('APG_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('calculate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialDayGrant',
            fields=[
                ('sdg_id', models.AutoField(primary_key=True, serialize=False)),
                ('occasion_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubsidyYear',
            fields=[
                ('sy_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_range', models.CharField(max_length=50)),
                ('y_subsidy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FuelSubsidy',
            fields=[
                ('fs_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_subsidy', models.IntegerField()),
                ('fuel_price', models.BigIntegerField()),
                ('pos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhoneSubsidy',
            fields=[
                ('mb', models.AutoField(primary_key=True, serialize=False)),
                ('grant', models.BigIntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeWork',
            fields=[
                ('ot_id', models.AutoField(primary_key=True, serialize=False)),
                ('grant', models.BigIntegerField(blank=True, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
        migrations.CreateModel(
            name='SubsidyPosition',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False)),
                ('grant', models.BigIntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
    ]
