# Generated by Django 5.1.4 on 2024-12-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_myapp_lcic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_myapp_lcic',
            new_name='Employee_lcic',
        ),
    ]
