# Generated by Django 5.1.4 on 2025-05-13 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_annualperformancegrant_specialdaygrant_subsidyyear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_lcic',
            name='position',
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='pos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
    ]
