# Generated by Django 5.1.4 on 2024-12-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_employee_myapp_lcic_employee_lcic'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(max_length=50)),
                ('Tdeteil', models.CharField(max_length=255)),
                ('Tfrom', models.CharField(max_length=100)),
                ('Tplace', models.CharField(max_length=100)),
                ('Command', models.CharField(max_length=150)),
                ('Tdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Document_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=255)),
                ('Sender', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=100)),
            ],
        ),
    ]
