# Generated by Django 5.1.4 on 2024-12-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_activity_document_out_documententry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogin',
            options={},
        ),
    ]
