# Generated by Django 5.1.4 on 2025-05-13 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_employee_lcic_position_employee_lcic_pos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('mp_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fuel_subsidy', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('phone_subsidy', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_day_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
    ]
