# Generated by Django 5.1.4 on 2024-12-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userlogin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogin',
            options={'managed': False},
        ),
    ]
