# Generated by Django 5.1.4 on 2025-05-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_systemuser_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyPayment',
        ),
    ]
