# Generated by Django 5.1.4 on 2025-05-14 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_monthlypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayroll',
            fields=[
                ('mp_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ot_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
                ('fuel_subsidy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fuelsubsidy')),
                ('overtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.overtimework')),
                ('position_subsidy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subsidyposition')),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.salary')),
                ('subsidy_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subsidyyear')),
            ],
        ),
    ]
