# Generated by Django 5.1.4 on 2025-05-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_monthlypayroll_fuel_payment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyPayroll',
            new_name='MonthlyPayment',
        ),
    ]
