# Generated by Django 5.1.4 on 2025-05-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_monthlypayroll_monthlypayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalaryGrade',
            new_name='Salary_Grade',
        ),
        migrations.AlterField(
            model_name='fuelsubsidy',
            name='fuel_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelsubsidy',
            name='fuel_subsidy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
