# Generated by Django 5.1.4 on 2025-05-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_salarygrade_salary_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidyyear',
            name='y_subsidy',
            field=models.BigIntegerField(),
        ),
    ]
