# Generated by Django 5.1.4 on 2025-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_subsidyyear_y_subsidy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidyyear',
            name='y_subsidy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
