# Generated by Django 5.1.4 on 2024-12-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_birthplace_remove_employee_lcic_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('village', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
            ],
        ),
    ]
