# Generated by Django 5.1.4 on 2024-12-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_current_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='current_address',
        ),
    ]
