# Generated by Django 5.1.4 on 2025-05-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_subsidyyear_y_subsidy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidyyear',
            name='year_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
