# Generated by Django 5.1.4 on 2024-12-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_current_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_lcic',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='percent_95',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='salary_grade',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='status',
        ),
    ]
