# Generated by Django 5.1.4 on 2025-05-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_subsidyyear_year_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/'),
        ),
    ]
