# Generated by Django 5.1.4 on 2024-12-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_province_lcic_delete_birthplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(blank=True, null=True)),
                ('Prov_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Dstr_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('District_Name', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(blank=True, null=True)),
                ('Prov_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Dstr_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Vill_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Village_Name', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
    ]
