# Generated by Django 5.1.4 on 2025-05-19 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_monthlypayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_lcic',
            name='date_add',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
