# Generated by Django 5.1.4 on 2024-12-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_district_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documententry',
            name='document',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documententry',
            name='file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documententry',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
