# Generated by Django 5.1.4 on 2024-12-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_district_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_login',
                'managed': False,
            },
        ),
    ]
