# Generated by Django 5.1.4 on 2025-05-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_document_lcic_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsubsidy',
            name='total_fuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
