# Generated by Django 5.1.4 on 2024-12-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_lcic_login_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LCIC_Login',
        ),
    ]
