# Generated by Django 5.1.4 on 2025-05-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_systemsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelsubsidy',
            name='fuel_price',
        ),
    ]
