# Generated by Django 5.1.4 on 2025-05-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_fuelsubsidy_fuel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidyposition',
            name='grant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
