# Generated by Django 5.1.4 on 2025-05-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_subsidyposition_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsubsidy',
            name='fuel_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
