# Generated by Django 5.1.4 on 2025-05-20 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_fuelsubsidy_fuel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsubsidy',
            name='fuel_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.systemsetting'),
        ),
    ]
