# Generated by Django 5.1.4 on 2025-01-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_document_out_dmo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_out',
            name='id',
        ),
        migrations.RemoveField(
            model_name='documententry',
            name='id',
        ),
        migrations.AddField(
            model_name='document_out',
            name='dmo_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documententry',
            name='dme_id',
            field=models.AutoField(default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
