# Generated by Django 5.1.4 on 2025-01-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_document_out_id_remove_documententry_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document_out',
            old_name='dmo_id',
            new_name='id',
        ),
    ]
