# Generated by Django 5.1.4 on 2025-05-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_fuelsubsidy_fuel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='ot_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
