# Generated by Django 5.1.4 on 2025-01-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_dmo_id_document_out_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document_out',
            old_name='id',
            new_name='dmo_id',
        ),
    ]
