# Generated by Django 5.1.4 on 2025-05-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_monthlypayment_ot_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlypayment',
            old_name='emp',
            new_name='emp_id',
        ),
    ]
