# Generated by Django 5.1.4 on 2025-01-07 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_documententry_documentin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documentin',
        ),
        migrations.DeleteModel(
            name='Documentout',
        ),
    ]
