# Generated by Django 5.1.4 on 2025-05-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_emp_monthlypayment_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_lcic',
            name='year',
            field=models.CharField(null=True),
        ),
    ]
