# Generated by Django 5.1.4 on 2025-01-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_delete_documentin_delete_documentout'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_lcic',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('insert_date', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('document_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
