# Generated by Django 5.1.4 on 2025-05-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_employee_lcic_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_lcic',
            old_name='year',
            new_name='age_entry',
        ),
    ]
