# Generated by Django 5.1.4 on 2025-05-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_year_employee_lcic_age_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='total_subsidy_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
