# Generated by Django 5.1.4 on 2025-05-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_monthlypayment_total_subsidy_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsubsidy',
            name='fuel_subsidy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
