# Generated by Django 5.1.4 on 2025-01-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_document_lcic_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_lcic',
            old_name='field_of_study',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='employee_lcic',
            old_name='percent_95',
            new_name='date_95_percent',
        ),
        migrations.RenameField(
            model_name='employee_lcic',
            old_name='name_E',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='employee_lcic',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='employee_lcic',
            old_name='name_L',
            new_name='eng_name',
        ),
        migrations.RenameField(
            model_name='employee_lcic',
            old_name='employment_date',
            new_name='join_date',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='employment_years',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='labor_union',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='youth_full',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='youth_reserve',
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='Education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='age',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='birth_place',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='date_full_party',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='date_support_party',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='date_theory_training',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='ethnicity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='female_member',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='graduated_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='lao_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='marital_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='party_training',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='perm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='salary_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='study_sponsor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='union_member',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='years_party',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='years_service',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='youth_member',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_lcic',
            name='current_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee_lcic',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_lcic',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
