# Generated by Django 5.1.4 on 2025-05-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_fuelsubsidy_fuel_subsidy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlypayment',
            old_name='overtime',
            new_name='ot_id',
        ),
    ]
