# Generated by Django 5.1.4 on 2025-01-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_field_of_study_employee_lcic_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_format',
            fields=[
                ('dmf_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('dmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
