# Generated by Django 5.1.4 on 2025-05-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_overtime_monthlypayment_ot_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary_Grade',
        ),
    ]
