# Generated by Django 5.1.4 on 2025-05-26 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_delete_salary_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilephonesubsidy',
            name='position',
        ),
        migrations.RemoveField(
            model_name='overtimework',
            name='position',
        ),
        migrations.RemoveField(
            model_name='subsidyposition',
            name='position',
        ),
        migrations.AddField(
            model_name='mobilephonesubsidy',
            name='pos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
        migrations.AddField(
            model_name='overtimework',
            name='pos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
        migrations.AddField(
            model_name='position',
            name='fs_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fuelsubsidy'),
        ),
        migrations.AddField(
            model_name='position',
            name='mb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mobilephonesubsidy'),
        ),
        migrations.AddField(
            model_name='position',
            name='ot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.overtimework'),
        ),
        migrations.AddField(
            model_name='position',
            name='sal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salary'),
        ),
        migrations.AddField(
            model_name='position',
            name='sp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subsidyposition'),
        ),
        migrations.AddField(
            model_name='position',
            name='sy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subsidyyear'),
        ),
        migrations.AddField(
            model_name='subsidyposition',
            name='pos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
        migrations.AlterField(
            model_name='fuelsubsidy',
            name='pos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
    ]
