# Generated by Django 5.1.4 on 2025-01-16 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_section_document_lcic_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='doc_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.document_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document_lcic',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.document_format'),
            preserve_default=False,
        ),
    ]
