# Generated by Django 5.1.4 on 2025-05-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_mobilephonesubsidy_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='sy_id',
        ),
    ]
