# Generated by Django 5.1.4 on 2025-01-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_document_lcic_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='doc_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
