# Generated by Django 5.1.4 on 2025-05-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_position_sy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='fs_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='mb',
        ),
        migrations.RemoveField(
            model_name='position',
            name='ot_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='sal_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='sp_id',
        ),
    ]
