# Generated by Django 5.1.4 on 2025-05-27 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_position_fs_id_remove_position_mb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='date_add',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='document_lcic',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
