# Generated by Django 5.1.4 on 2025-01-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_systemlogins_user_id_systemlogins_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemlogins',
            name='id',
        ),
        migrations.RemoveField(
            model_name='systemlogins',
            name='user',
        ),
        migrations.AddField(
            model_name='systemlogins',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemlogins',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
