# Generated by Django 5.1.4 on 2025-01-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_systemlogins_id_remove_systemlogins_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='systemlogins',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
