# Generated by Django 5.1.4 on 2025-05-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_overtimework_csd_evening_overtimework_csd_night_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimework',
            name='pos_id',
        ),
        migrations.AddField(
            model_name='overtimework',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic'),
        ),
    ]
