# Generated by Django 5.1.4 on 2025-01-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_delete_systemlogins_delete_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
