# Generated by Django 5.1.4 on 2025-01-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_systemuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.department'),
            preserve_default=False,
        ),
    ]
