# Generated by Django 5.1.4 on 2025-06-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_monthly_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_payment',
            name='fue_subsidy',
        ),
        migrations.RemoveField(
            model_name='monthly_payment',
            name='ot_id',
        ),
        migrations.AddField(
            model_name='monthly_payment',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
