# Generated by Django 5.1.4 on 2025-06-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_monthly_payment_fue_subsidy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimework',
            old_name='grant',
            new_name='total_ot',
        ),
    ]
