# Generated by Django 5.1.4 on 2025-01-30 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_employee_lcic_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='Employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic'),
            preserve_default=False,
        ),
    ]
