# Generated by Django 5.1.4 on 2025-06-03 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_rename_grant_overtimework_total_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_payment',
            name='sy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subsidyyear'),
        ),
    ]
