# Generated by Django 5.1.4 on 2025-01-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_systemuser_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='Status',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
