# Generated by Django 5.1.4 on 2025-06-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_monthly_payment_sy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_format',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
