# Generated by Django 5.1.4 on 2025-01-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_systemuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='Status',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
