# Generated by Django 5.1.4 on 2025-06-04 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_systemsetting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDay_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
                ('special_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialdaygrant')),
            ],
        ),
        migrations.AddField(
            model_name='specialdaygrant',
            name='pos_id',
            field=models.ManyToManyField(blank=True, through='api.SpecialDay_Position', to='api.position'),
        ),
    ]
