# Generated by Django 5.1.4 on 2025-02-04 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_document_lcic_department_into_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='department_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_lcic_department_into', to='api.department'),
        ),
    ]
