# Generated by Django 5.1.4 on 2025-06-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_specialday_position_specialdaygrant_pos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialday_position',
            name='grant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
