# Generated by Django 5.1.4 on 2025-06-06 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_specialday_position_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='col_policy',
            fields=[
                ('col_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('Number_of_days', models.IntegerField(blank=True, null=True)),
                ('amount_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('job_mobility_policy', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
            ],
        ),
    ]
