# Generated by Django 5.1.4 on 2025-02-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_document_lcic_department_into'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_lcic',
            name='status',
            field=models.BooleanField(default=False, verbose_name='ອ່ານແລ້ວ'),
        ),
    ]
