# Generated by Django 5.1.4 on 2025-02-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_document_lcic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_lcic',
            name='doc_type_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
