# Generated by Django 5.1.4 on 2025-06-09 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_col_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimework',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
