# Generated by Django 5.1.4 on 2025-02-04 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_document_lcic_doc_type_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_lcic',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.department'),
            preserve_default=False,
        ),
    ]
