# Generated by Django 5.1.4 on 2025-06-09 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_overtimework_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_payment',
            fields=[
                ('fp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic')),
                ('pos_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
    ]
