# Generated by Django 5.1.4 on 2025-06-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_fuel_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel_payment',
            name='pos_id',
        ),
    ]
