# Generated by Django 5.1.4 on 2025-02-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_employee_lcic_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='status',
        ),
    ]
