# Generated by Django 5.1.4 on 2025-06-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_fuel_payment_pos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_mobility',
            fields=[
                ('jm_id', models.AutoField(primary_key=True, serialize=False)),
                ('jm_policy', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pos_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
        migrations.AlterField(
            model_name='col_policy',
            name='job_mobility_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.job_mobility'),
        ),
    ]
