# Generated by Django 5.1.4 on 2025-02-05 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_systemuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='Status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.status'),
            preserve_default=False,
        ),
    ]
