# Generated by Django 5.1.4 on 2025-06-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_job_mobility_alter_col_policy_job_mobility_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_policy',
            name='job_mobility_policy',
        ),
    ]
