# Generated by Django 5.1.4 on 2025-06-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_remove_col_policy_job_mobility_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_policy',
            name='amount_per_day',
        ),
        migrations.AddField(
            model_name='job_mobility',
            name='amount_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
