# Generated by Django 5.1.4 on 2025-02-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_remove_systemuser_status_systemuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='status',
            field=models.CharField(choices=[('new', 'ໃໝ່'), ('viewed', 'ເບີ່ງແລ້ວ')], default='new', max_length=10),
        ),
    ]
