# Generated by Django 5.1.4 on 2025-02-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_document_lcic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_lcic',
            name='department_into',
        ),
        migrations.AddField(
            model_name='document_lcic',
            name='department_into',
            field=models.ManyToManyField(blank=True, related_name='document_lcic_department_into', to='api.department'),
        ),
    ]
