# Generated by Django 5.1.4 on 2025-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_col_policy_amount_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_policy',
            name='Number_of_days',
        ),
        migrations.AddField(
            model_name='job_mobility',
            name='Number_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
