# Generated by Django 5.1.4 on 2025-06-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_remove_col_policy_number_of_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_mobility',
            old_name='Number_of_days',
            new_name='number_of_days',
        ),
    ]
