# Generated by Django 5.1.4 on 2025-02-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_remove_document_lcic_department_into_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
