# Generated by Django 5.1.4 on 2025-02-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_document_lcic_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_lcic',
            name='birth_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='salary_level',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='years_of_service',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
