# Generated by Django 5.1.4 on 2025-06-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_rename_number_of_days_job_mobility_number_of_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyPayment',
        ),
    ]
