# Generated by Django 5.1.4 on 2025-02-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_employee_lcic_birth_date_employee_lcic_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_lcic',
            name='birth_date',
            field=models.CharField(max_length=50),
        ),
    ]
