# Generated by Django 5.1.4 on 2025-06-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_delete_monthlypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('ot_id', models.CharField(max_length=10)),
                ('emp_id', models.CharField(max_length=255)),
                ('csd_evening', models.CharField(default='0.00', max_length=20)),
                ('csd_night', models.CharField(default='0.00', max_length=20)),
                ('hd_mor_after', models.CharField(default='0.00', max_length=20)),
                ('hd_evening', models.CharField(default='0.00', max_length=20)),
                ('hd_night', models.CharField(default='0.00', max_length=20)),
                ('total_ot', models.CharField(default='0', max_length=20)),
                ('salary', models.CharField(max_length=50)),
                ('value_150', models.CharField(default='0', max_length=20)),
                ('value_200', models.CharField(default='0', max_length=20)),
                ('value_250', models.CharField(default='0', max_length=20)),
                ('value_300', models.CharField(default='0', max_length=20)),
                ('value_350', models.CharField(default='0', max_length=20)),
            ],
        ),
    ]
