# Generated by Django 5.1.4 on 2025-06-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_overtime_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime_history',
            name='emp_id',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
