# Generated by Django 5.1.4 on 2025-02-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_employee_lcic_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_lcic',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='salary_level',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='years_of_service',
        ),
    ]
