# Generated by Django 5.1.4 on 2025-06-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_overtime_history_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime_history',
            name='emp_id',
            field=models.BigIntegerField(),
        ),
    ]
