# Generated by Django 5.1.4 on 2025-02-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_employee_lcic_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_lcic',
            name='birth_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
