# Generated by Django 5.1.4 on 2025-02-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_employee_lcic_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_lcic',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
