# Generated by Django 5.1.4 on 2025-06-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_overtime_history_ot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime_history',
            name='csd_evening',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='csd_night',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='hd_evening',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='hd_mor_after',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='hd_night',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='total_ot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='value_150',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='value_200',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='value_250',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='value_300',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime_history',
            name='value_350',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
