# Generated by Django 5.1.4 on 2025-06-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_overtime_history_csd_evening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime_history',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
