# Generated by Django 5.1.4 on 2025-02-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_employee_lcic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_lcic',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
