# Generated by Django 5.1.4 on 2025-02-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_employee_lcic_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_lcic',
            name='SalaryGrade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.salarygrade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='years_of_service',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
