# Generated by Django 5.1.4 on 2025-06-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_overtime_history_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimework',
            old_name='hd_Mor_after',
            new_name='hd_mor_after',
        ),
    ]
