# Generated by Django 5.1.4 on 2025-02-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_employee_lcic_salarygrade_employee_lcic_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_lcic',
            name='SalaryGrade',
        ),
    ]
