# Generated by Django 5.1.4 on 2025-02-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_remove_employee_lcic_salarygrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_lcic',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='employee_lcic',
            name='years_of_service',
        ),
    ]
