# Generated by Django 5.1.4 on 2025-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_salary_salarygrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='SalaryGrade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
