# Generated by Django 5.1.4 on 2025-02-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_remove_employee_lcic_phone_remove_employee_lcic_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_lcic',
            name='years_of_service',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
