# Generated by Django 5.1.4 on 2025-06-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_salary_salarygrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='colpolicy_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('col_id', models.BigIntegerField()),
                ('emp_id', models.BigIntegerField()),
                ('position', models.CharField(max_length=255)),
                ('number_of_days', models.CharField(max_length=10)),
                ('amount_per_day', models.CharField(max_length=20)),
                ('amount_of_money', models.CharField(max_length=20)),
                ('job_mobility_policy', models.CharField(max_length=20)),
                ('total_paymant', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='overtime_history',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
