# Generated by Django 5.1.4 on 2025-06-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_colpolicy_history_overtime_history_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colpolicy_history',
            name='position',
        ),
        migrations.RemoveField(
            model_name='overtime_history',
            name='position',
        ),
        migrations.AddField(
            model_name='colpolicy_history',
            name='pos_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overtime_history',
            name='pos_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
