# Generated by Django 5.1.4 on 2025-06-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_colpolicy_history_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colpolicy_history',
            old_name='amount_of_money',
            new_name='total_amount',
        ),
    ]
