# Generated by Django 5.1.4 on 2025-06-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_rename_amount_of_money_colpolicy_history_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colpolicy_history',
            old_name='job_mobility_policy',
            new_name='jm_policy',
        ),
    ]
