# Generated by Django 5.1.4 on 2025-02-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_employee_lcic_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_general',
            fields=[
                ('docg_id', models.AutoField(primary_key=True, serialize=False)),
                ('insert_date', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(null=True, upload_to='documents_general/')),
                ('document_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_lcic_general', to='api.department')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document_format')),
            ],
        ),
    ]
