# Generated by Django 5.1.4 on 2025-02-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_document_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('eth', models.CharField(max_length=100)),
                ('rel', models.CharField(max_length=100)),
                ('b_vill', models.CharField(max_length=100)),
                ('b_dist', models.CharField(max_length=100)),
                ('b_prov', models.CharField(max_length=100)),
                ('c_vill', models.CharField(max_length=100)),
                ('c_dist', models.CharField(max_length=100)),
                ('c_prov', models.CharField(max_length=100)),
                ('gov_entry', models.DateField()),
                ('youth_date', models.DateField(blank=True, null=True)),
                ('women_date', models.DateField(blank=True, null=True)),
                ('union_date', models.DateField(blank=True, null=True)),
                ('party_cand_date', models.DateField(blank=True, null=True)),
                ('full_party_date', models.DateField(blank=True, null=True)),
                ('curr_party_pos', models.CharField(blank=True, max_length=255, null=True)),
                ('party_apt_date', models.DateField(blank=True, null=True)),
                ('curr_gov_pos', models.CharField(blank=True, max_length=255, null=True)),
                ('gov_apt_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
