# Generated by Django 5.1.4 on 2025-06-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_rename_total_paymant_colpolicy_history_total_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuel_payment_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fp_id', models.BigIntegerField()),
                ('update_date', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_id', models.BigIntegerField()),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_subsidy', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_price', models.CharField(blank=True, max_length=50, null=True)),
                ('total_fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
