# Generated by Django 5.1.4 on 2025-06-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_fuel_payment_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel_payment_history',
            name='created_at',
        ),
    ]
