# Generated by Django 5.1.4 on 2025-02-11 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_personalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('dom_abrd', models.CharField(max_length=50)),
                ('per_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personalinformation')),
            ],
        ),
    ]
