# Generated by Django 5.1.4 on 2025-06-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_remove_fuel_payment_history_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel_payment_history',
            old_name='update_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='fuelsubsidy',
            old_name='update_date',
            new_name='date',
        ),
    ]
