# Generated by Django 5.1.4 on 2025-02-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='dob',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gov_entry',
            field=models.CharField(max_length=100),
        ),
    ]
