# Generated by Django 5.1.4 on 2025-06-13 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_rename_update_date_fuel_payment_history_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='col_policy',
            name='date',
        ),
    ]
