# Generated by Django 5.1.4 on 2025-02-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_specializededucation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('sid_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
