# Generated by Django 5.1.4 on 2025-06-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_remove_col_policy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_mobility',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
