# Generated by Django 5.1.4 on 2025-02-11 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_sidebar'),
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('sid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sidebar')),
            ],
        ),
    ]
