# Generated by Django 5.1.4 on 2025-06-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_job_mobility_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_payment',
            name='sy_id',
        ),
    ]
