# Generated by Django 5.1.4 on 2025-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_remove_monthly_payment_sy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime_history',
            name='emp_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='overtime_history',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
