# Generated by Django 5.1.4 on 2025-02-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='id',
            new_name='sta_id',
        ),
    ]
