# Generated by Django 5.1.4 on 2025-02-11 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_rename_id_status_sta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='sta_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.status'),
            preserve_default=False,
        ),
    ]
