# Generated by Django 5.1.4 on 2025-02-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_roles_sta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='sid_id',
            new_name='sid',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='sta_id',
            new_name='sta',
        ),
    ]
