# Generated by Django 5.1.4 on 2025-02-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_rename_sid_id_roles_sid_rename_sta_id_roles_sta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='sid',
            new_name='Sidebar_sid',
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='sta',
            new_name='Status_sta',
        ),
    ]
