# Generated by Django 5.1.4 on 2025-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_alter_systemsetting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='income_tax',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('lvl', models.PositiveIntegerField(unique=True)),
                ('incom_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=12)),
                ('each_level_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('all_tax', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
