# Generated by Django 5.1.4 on 2025-02-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_rename_sid_roles_sidebar_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_lcic',
            name='years_of_service',
            field=models.CharField(),
        ),
    ]
