# Generated by Django 5.1.4 on 2025-06-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_income_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_tax',
            name='incom_base',
            field=models.CharField(max_length=35),
        ),
    ]
