# Generated by Django 5.1.4 on 2025-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_employee_lcic_years_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='icon',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebar',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='sidebar_roles', to='api.status'),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='roles',
        ),
    ]
