# Generated by Django 5.1.4 on 2025-06-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_income_tax_incom_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_tax',
            name='all_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
