# Generated by Django 5.1.4 on 2025-02-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_sidebar_icon_sidebar_roles_sidebar_url_delete_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='roles',
        ),
    ]
