# Generated by Django 5.1.4 on 2025-06-20 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_alter_income_tax_all_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_payment',
            name='child_Subsidy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='monthly_payment',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthly_payment',
            name='health_Subsidy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Saving_cooperative',
            fields=[
                ('sc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ເງິນກູ້')),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ດອກເບັ້ຍ')),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ເງິນຝາກ')),
                ('date', models.DateField(auto_now=True, verbose_name='ວັນທີບັນທຶກ')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic', verbose_name='ພະນັກງານ')),
            ],
        ),
    ]
