# Generated by Django 5.1.4 on 2025-06-20 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_monthly_payment_child_subsidy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving_cooperative',
            name='Loan_deduction_194',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saving_cooperative',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saving_cooperative',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saving_cooperative',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee_lcic'),
        ),
        migrations.AlterField(
            model_name='saving_cooperative',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saving_cooperative',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
