# Generated by Django 5.1.4 on 2025-02-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_remove_sidebar_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='sidebar',
            name='url',
        ),
    ]
