# Generated by Django 5.1.4 on 2025-02-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_status_icon_status_roles_status_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='roles',
            new_name='Sidebar',
        ),
        migrations.RemoveField(
            model_name='status',
            name='url',
        ),
    ]
