# Generated by Django 5.1.4 on 2025-06-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_remove_monthly_payment_total_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly_payment',
            old_name='children',
            new_name='child',
        ),
    ]
