# Generated by Django 5.1.4 on 2025-06-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_rename_children_monthly_payment_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialday_position',
            old_name='position',
            new_name='pos_id',
        ),
        migrations.RemoveField(
            model_name='specialdaygrant',
            name='pos_id',
        ),
    ]
