# Generated by Django 5.1.4 on 2025-02-13 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_sidebar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_lcic',
            name='per_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.personalinformation'),
            preserve_default=False,
        ),
    ]
