# Generated by Django 5.1.4 on 2025-02-13 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_employee_lcic_per_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_lcic',
            name='per_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.personalinformation'),
        ),
    ]
