# Generated by Django 5.1.4 on 2025-02-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_alter_employee_lcic_per_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_lcic',
            name='per_id',
        ),
    ]
