# Generated by Django 5.1.4 on 2025-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_remove_employee_lcic_per_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='status',
            field=models.CharField(choices=[('sabide', 'ໃໝ່'), ('viewed', 'ເບີ່ງແລ້ວ')], default='new', max_length=10),
        ),
    ]
