# Generated by Django 5.1.4 on 2025-02-19 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_alter_document_lcic_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'ໃໝ່'), ('viewed', 'ເບີ່ງແລ້ວ')], default='new', max_length=10)),
                ('read_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_documents', to='api.department')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='api.document_lcic')),
            ],
        ),
    ]
