# Generated by Django 5.1.4 on 2025-02-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_documentreadstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentReadStatus',
        ),
    ]
