# Generated by Django 5.1.4 on 2025-02-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_lcic',
            name='status',
        ),
        migrations.AddField(
            model_name='document_lcic',
            name='status',
            field=models.ManyToManyField(blank=True, through='api.Document_Status', to='api.systemuser'),
        ),
    ]
