# Generated by Django 5.1.4 on 2025-02-20 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_remove_document_lcic_status_document_lcic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_status',
            name='doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.document_lcic'),
        ),
        migrations.AlterField(
            model_name='document_status',
            name='us_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_statuses', to='api.systemuser'),
        ),
    ]
