# Generated by Django 5.1.4 on 2025-02-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_alter_document_status_doc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_general',
            name='doc_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
