# Generated by Django 5.1.4 on 2025-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_document_general_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='status',
            field=models.ManyToManyField(default='0', through='api.Document_Status', to='api.systemuser'),
        ),
    ]
