# Generated by Django 5.1.4 on 2025-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_alter_document_lcic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='status',
            field=models.ManyToManyField(blank=True, through='api.Document_Status', to='api.systemuser'),
        ),
    ]
