# Generated by Django 5.1.4 on 2025-02-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_alter_document_lcic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_lcic',
            name='status2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.document_status'),
            preserve_default=False,
        ),
    ]
