# Generated by Django 5.1.4 on 2025-02-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_document_lcic_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_lcic',
            name='status2',
        ),
    ]
