# Generated by Django 5.1.4 on 2025-02-20 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_remove_document_lcic_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_lcic',
            name='status2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.document_status'),
        ),
    ]
