# Generated by Django 5.1.4 on 2025-02-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_remove_document_lcic_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_lcic',
            name='status2',
            field=models.CharField(choices=[('new', 'ໃໝ່'), ('viewed', 'ເບີ່ງແລ້ວ')], default='new', max_length=10),
        ),
    ]
