# Generated by Django 5.1.4 on 2025-02-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_document_lcic_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_general',
            name='doc_type',
        ),
    ]
