# Generated by Django 5.1.4 on 2025-02-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_award_disciplinaryaction_evaluation_familymember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_status',
            name='Doc_status',
            field=models.CharField(choices=[('new', 'ໃໝ່'), ('viewed', 'ເບີ່ງແລ້ວ')], default='new', max_length=10),
        ),
    ]
