# Generated by Django 5.1.4 on 2025-02-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_document_status_doc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_status',
            name='Doc_status',
            field=models.CharField(default='viewed', max_length=10),
        ),
    ]
