# Generated by Django 5.1.4 on 2025-02-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_alter_document_status_doc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='status2',
            field=models.CharField(default='new', max_length=10),
        ),
    ]
