# Generated by Django 5.1.4 on 2025-02-25 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_alter_document_lcic_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_status',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document_statuses', to='api.department'),
            preserve_default=False,
        ),
    ]
