# Generated by Django 5.1.4 on 2025-02-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_document_status_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_status',
            name='department',
        ),
    ]
