# Generated by Django 5.1.4 on 2025-02-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_remove_document_status_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document_status',
            unique_together={('doc_id', 'us_id')},
        ),
    ]
