# Generated by Django 5.1.4 on 2025-02-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_alter_document_status_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignlanguage',
            name='prof',
            field=models.CharField(max_length=50),
        ),
    ]
