# Generated by Django 5.1.4 on 2025-02-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_alter_foreignlanguage_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_lcic',
            name='years_of_service',
        ),
        migrations.AddField(
            model_name='employee_lcic',
            name='year_entry',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
