# Generated by Django 5.1.4 on 2025-02-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_remove_employee_lcic_years_of_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_lcic',
            name='year_entry',
            field=models.CharField(),
        ),
    ]
