# Generated by Django 5.1.4 on 2025-02-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_alter_employee_lcic_year_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_lcic',
            name='year_entry',
        ),
    ]
