# Generated by Django 5.1.4 on 2025-02-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_remove_employee_lcic_year_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_lcic',
            name='year_entry',
            field=models.CharField(null=True),
        ),
    ]
