# Generated by Django 5.1.4 on 2025-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_employee_lcic_year_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_lcic',
            name='pic',
            field=models.ImageField(null=True, upload_to='emp_img/'),
        ),
    ]
