# Generated by Django 5.1.4 on 2025-03-11 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_alter_employee_lcic_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_format',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
    ]
