# Generated by Django 5.1.4 on 2025-03-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_document_format_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_format',
            name='insert_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document_format',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='document_format',
            name='us_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.systemuser'),
        ),
    ]
