# Generated by Django 5.1.4 on 2025-03-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_document_format_insert_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_format',
            name='insert_date',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
