# Generated by Django 5.1.4 on 2025-03-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_alter_document_format_insert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_format',
            name='insert_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
