# Generated by Django 5.1.4 on 2025-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_alter_document_format_insert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_format',
            name='insert_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
