# Generated by Django 5.1.4 on 2025-03-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_alter_document_format_insert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_lcic',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
