# Generated by Django 5.1.4 on 2025-03-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_alter_document_lcic_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
