# Generated by Django 5.1.4 on 2025-03-17 09:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_alter_document_lcic_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_lcic',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.department_directory_path),
        ),
    ]
