# Generated by Django 5.1.4 on 2025-03-17 09:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_alter_document_lcic_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_general',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.general_document_directory_path),
        ),
    ]
