# Generated by Django 5.1.4 on 2025-03-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_alter_document_general_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_general',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
