# Generated by Django 5.1.4 on 2025-03-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_document_general_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_general',
            name='endate_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='document_general',
            name='status_doc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='document_general',
            name='insert_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
