# Generated by Django 5.1.4 on 2025-03-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_document_general_endate_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_general',
            name='endate_date',
        ),
        migrations.AddField(
            model_name='document_general',
            name='en_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
