# Generated by Django 5.1.4 on 2025-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_remove_document_general_endate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_general',
            name='status_doc',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
