# Generated by Django 5.1.4 on 2025-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_alter_document_general_status_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_general',
            name='status_doc',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
